// // var btn = document.getElementById("btn-click");

// // //using query selector 
// // var mainDiv = document.querySelector("header div")
// // console.log(mainDiv)
// // function onBtnClick(){
// //     //changeing bg color or style
// //     btn.style.backgroundColor = "yellow"
// //     // alert('button is alert')
// // }
// // //EVENT PROPERTIES ONCLICK,ONPAUSE,ONPLAY
// // // btn.onclick = function(){
// // //     alert("Button Clicked!")
// // //     console.log("button is clicked!")
// // // }
// // //this will automatically alert th webpage
// // // btn.onclick = onBtnClick();

// // //adding event listeners
// // //we can write any event listener property like hover click
// // // btn.addEventListener('click',function(){
// // //     alert("anonymous function called")
// // // })
// // btn.addEventListener('click', onBtnClick)

// var btn = document.getElementById('btn-click');
// var mainDiv = document.querySelector("header div")
// // console.log(mainDiv)
// function onmouseover(){
//     //generate random num 0 to 255
//     var randomNum = Math.floor(Math.random() * 255);
//     // alert(randomNum);
//     //only first value is generated by variable num
//     // alert("rgb(" + randomNum + " ," + 45 + "," + 155 + ")");
//     //to change all the rgb numbers
//     // alert("rgb(" + Math.floor(Math.random() * 255)+ "," +
//     //  Math.floor(Math.random() *255) + "," 
//     //  +  Math.floor(Math.random() * 255) + ")");
//     mainDiv.style.backgroundColor = "rgb(" + Math.floor(Math.random() * 255)+ "," +
//     Math.floor(Math.random() *255) + "," 
//     +  Math.floor(Math.random() * 255) + ")";
//     //generate random color in js
//     //with math random in js
//     //these comes with digit or floating numbers
//     //for int numbers with random values
//     // alert(Math.floor(Math.random() * 255))
//     // alert(Math.random() * 255);
//     // mainDiv.style.backgroundColor = "lightcoral"
// }
// // btn.addEventListener('click', onBtnClick);

// btn.addEventListener("mouseover", onmouseover)


//  var btn = document.getElementById("btn-click");
//  var mainDiv = document.querySelector("header div")
//  function onBtnClick(){
//     mainDiv.style.backgroundColor = 'red' 

//  }

// btn.addEventListener('click', onBtnClick)

// $("header div").click(function () {
//     // $("#circle").css("width", "400px");
//                 $("header div").css("background-color", "red");
// //                 // alert($("#circle").css("background-color", "red"));
// //                 //$("#circle").css("display", "none");
// //                 // $("div").click(function () {
// //                 // $(this).css("background-color", "orangered");

// });
//in vanilla js

